// aigc-site-react/src/components/script/ScriptRewriteDialog.tsx
import { AppInput } from '@/components/common/AppInput'
import { AppButton } from '@/components/common/AppButton'
import { ScriptRewriteDiffPanel, type RewriteDiffMode } from '@/components/script/ScriptRewriteDiffPanel'

type Props = {
  visible: boolean
  instruction: string
  targetStyle: string
  maxOutputChars: string
  originalText: string
  previewText: string
  diffMode: RewriteDiffMode
  loading?: boolean
  applying?: boolean
  previewSubtitle?: string
  onChangeInstruction: (value: string) => void
  onChangeTargetStyle: (value: string) => void
  onChangeMaxOutputChars: (value: string) => void
  onChangeDiffMode: (mode: RewriteDiffMode) => void
  onCancel: () => void
  onPreview: () => void
  onApply: () => void
}

export function ScriptRewriteDialog({
  visible,
  instruction,
  targetStyle,
  maxOutputChars,
  originalText,
  previewText,
  diffMode,
  loading,
  applying,
  previewSubtitle,
  onChangeInstruction,
  onChangeTargetStyle,
  onChangeMaxOutputChars,
  onChangeDiffMode,
  onCancel,
  onPreview,
  onApply,
}: Props) {
  if (!visible) return null
  return (
    <div className="dialog-overlay" role="dialog" aria-modal onClick={(e) => e.target === e.currentTarget && onCancel()}>
      <div className="dialog glass" style={{ maxWidth: 980 }}>
        <h3 className="dialog-title">AI 剧本改写</h3>
        <div style={{ display: 'grid', gap: 'var(--space-sm)' }}>
          <AppInput
            label="改写要求"
            as="textarea"
            rows={4}
            value={instruction}
            onChange={(v) => onChangeInstruction(String(v))}
            placeholder="例如：保持剧情主线不变，强化人物冲突与情绪递进，对白更自然。"
          />
          <AppInput
            label="目标风格（可选）"
            value={targetStyle}
            onChange={(v) => onChangeTargetStyle(String(v))}
            placeholder="例如：现实主义 + 悬疑张力"
          />
          <AppInput
            label="字数上限（可选）"
            value={maxOutputChars}
            onChange={(v) => onChangeMaxOutputChars(String(v))}
            placeholder="例如：4500"
          />
        </div>
        <div className="dialog-actions" style={{ marginTop: 'var(--space-md)' }}>
          <AppButton variant="ghost" loading={loading} onClick={onPreview}>
            预览改写
          </AppButton>
        </div>
        <div className="dialog-actions" style={{ marginTop: 'var(--space-sm)' }}>
          <button type="button" className={`btn-cancel ${diffMode === 'split' ? 'active' : ''}`} onClick={() => onChangeDiffMode('split')}>
            分栏对比
          </button>
          <button type="button" className={`btn-cancel ${diffMode === 'unified' ? 'active' : ''}`} onClick={() => onChangeDiffMode('unified')}>
            行内对比
          </button>
        </div>
        <div className="panel glass script-rewrite-diff-wrap">
          {previewSubtitle ? <p className="muted small">{previewSubtitle}</p> : null}
          <p className="muted small">对比基准：原始剧本</p>
          <ScriptRewriteDiffPanel originalText={originalText} rewrittenText={previewText} mode={diffMode} />
        </div>
        <div className="dialog-actions">
          <button type="button" className="btn-cancel" onClick={onCancel} disabled={!!loading || !!applying}>
            取消
          </button>
          <button type="button" className="btn-confirm" onClick={onApply} disabled={!!loading || !!applying || !previewText.trim()}>
            应用改写
          </button>
        </div>
      </div>
    </div>
  )
}

// aigc-site-vue-off/src/components/script/ScriptRewriteDialog.vue
<script setup lang="ts">
import AppInput from '@/components/common/AppInput.vue'
import ScriptRewriteDiffPanel from '@/components/script/ScriptRewriteDiffPanel.vue'
import type { RewriteDiffMode } from '@/components/script/ScriptRewriteDiffPanel.vue'

defineProps<{
  visible: boolean
  instruction: string
  targetStyle: string
  maxOutputChars: string
  originalText: string
  previewText: string
  diffMode: RewriteDiffMode
  loading?: boolean
  applying?: boolean
  previewSubtitle?: string
}>()

const emit = defineEmits<{
  (e: 'change:instruction', v: string): void
  (e: 'change:targetStyle', v: string): void
  (e: 'change:maxOutputChars', v: string): void
  (e: 'change:diffMode', v: RewriteDiffMode): void
  (e: 'cancel'): void
  (e: 'preview'): void
  (e: 'apply'): void
}>()
</script>

<template>
  <div v-if="visible" class="dialog-overlay" role="dialog" aria-modal @click.self="emit('cancel')">
    <div class="dialog glass" style="max-width: 980px">
      <h3 class="dialog-title">AI 剧本改写</h3>
      <div class="grid">
        <AppInput
          label="改写要求"
          as="textarea"
          :rows="4"
          :model-value="instruction"
          placeholder="例如：保持剧情主线不变，强化人物冲突与情绪递进。"
          @update:model-value="emit('change:instruction', String($event))"
        />
        <AppInput label="目标风格（可选）" :model-value="targetStyle" @update:model-value="emit('change:targetStyle', String($event))" />
        <AppInput
          label="字数上限（可选）"
          :model-value="maxOutputChars"
          placeholder="例如：4500"
          @update:model-value="emit('change:maxOutputChars', String($event))"
        />
      </div>
      <div class="dialog-actions">
        <button type="button" class="btn-submit" :disabled="loading" @click="emit('preview')">{{ loading ? '生成中...' : '预览改写' }}</button>
      </div>
      <div class="dialog-actions">
        <button type="button" class="btn-cancel" :class="{ active: diffMode === 'split' }" @click="emit('change:diffMode', 'split')">分栏对比</button>
        <button type="button" class="btn-cancel" :class="{ active: diffMode === 'unified' }" @click="emit('change:diffMode', 'unified')">行内对比</button>
      </div>
      <div class="panel glass script-rewrite-diff-wrap">
        <p v-if="previewSubtitle" class="muted small">{{ previewSubtitle }}</p>
        <p class="muted small">对比基准：原始剧本</p>
        <ScriptRewriteDiffPanel :original-text="originalText" :rewritten-text="previewText" :mode="diffMode" />
      </div>
      <div class="dialog-actions">
        <button type="button" class="btn-cancel" :disabled="loading || applying" @click="emit('cancel')">取消</button>
        <button type="button" class="btn-confirm" :disabled="loading || applying || !previewText.trim()" @click="emit('apply')">应用改写</button>
      </div>
    </div>
  </div>
</template>

<style scoped>
.grid {
  display: grid;
  gap: var(--space-sm);
}
</style>
