// aigc-site-react/src/components/history/Pagination.tsx
import { AppButton } from '@/components/common/AppButton'

type Props = {
  page: number
  totalPages: number
  onChange: (page: number) => void
}

export function Pagination({ page, totalPages, onChange }: Props) {
  return (
    <div className="pager">
      <AppButton size="sm" disabled={page <= 1} onClick={() => onChange(page - 1)}>
        上一页
      </AppButton>
      <span>
        第 {page} / {totalPages} 页
      </span>
      <AppButton size="sm" disabled={page >= totalPages} onClick={() => onChange(page + 1)}>
        下一页
      </AppButton>
    </div>
  )
}

// aigc-site-旧/src/components/history/Pagination.vue
<script setup lang="ts">
import AppButton from '@/components/common/AppButton.vue'

defineProps<{
  page: number
  totalPages: number
}>()

const emit = defineEmits<{
  (e: 'change', page: number): void
}>()
</script>

<template>
  <div class="pager">
    <AppButton size="sm" :disabled="page <= 1" @click="emit('change', page - 1)">上一页</AppButton>
    <span>第 {{ page }} / {{ totalPages }} 页</span>
    <AppButton size="sm" :disabled="page >= totalPages" @click="emit('change', page + 1)">下一页</AppButton>
  </div>
</template>

<style scoped>
.pager {
  margin-top: var(--space-lg);
  display: flex;
  align-items: center;
  justify-content: center;
  gap: var(--space-sm);
  flex-wrap: wrap;
}

span {
  color: var(--text-muted);
}
</style>
